# Generated by Django 3.0.4 on 2020-04-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200415_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='board',
            new_name='b',
        ),
    ]
