# Generated by Django 3.0.4 on 2020-04-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200417_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='b',
            new_name='boards',
        ),
    ]
