# Generated by Django 3.0.4 on 2020-04-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200417_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='boards',
            new_name='board',
        ),
    ]
