# Generated by Django 3.0.4 on 2020-04-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
