# Generated by Django 3.0.4 on 2020-04-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polls.Board'),
        ),
    ]
