# Generated by Django 3.0.4 on 2020-04-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200420_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
